/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const contextMenu: string;
const contextMenuItem: string;
const contextMenuItemWithIcon: string;
const contextMenuIcon: string;

export {
	contextMenu as "context-menu",
	contextMenu,
	contextMenuItem as "context-menu-item",
	contextMenuItem,
	contextMenuItemWithIcon as "context-menu-item-with-icon",
	contextMenuItemWithIcon,
	contextMenuIcon as "context-menu-icon",
	contextMenuIcon
};

export default {
	"context-menu": contextMenu,
	contextMenu,
	"context-menu-item": contextMenuItem,
	contextMenuItem,
	"context-menu-item-with-icon": contextMenuItemWithIcon,
	contextMenuItemWithIcon,
	"context-menu-icon": contextMenuIcon,
	contextMenuIcon
};
