/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const modalOverlay: string;
const modalContent: string;
const modalClose: string;
const modalButtonsContainer: string;
const modalButton: string;
const ok: string;
const cancel: string;

export {
	modalOverlay as "modal-overlay",
	modalOverlay,
	modalContent as "modal-content",
	modalContent,
	modalClose as "modal-close",
	modalClose,
	modalButtonsContainer as "modal-buttons-container",
	modalButtonsContainer,
	modalButton as "modal-button",
	modalButton,
	ok,
	cancel
};

export default {
	"modal-overlay": modalOverlay,
	modalOverlay,
	"modal-content": modalContent,
	modalContent,
	"modal-close": modalClose,
	modalClose,
	"modal-buttons-container": modalButtonsContainer,
	modalButtonsContainer,
	"modal-button": modalButton,
	modalButton,
	ok,
	cancel
};
