/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const choices: string;
const choiceWrapper: string;
const choiceWrapperBody: string;
const choiceWrapperFooter: string;
const choiceButton: string;
const choiceButtonImg: string;

export {
	choices,
	choiceWrapper as "choice-wrapper",
	choiceWrapper,
	choiceWrapperBody as "choice-wrapper-body",
	choiceWrapperBody,
	choiceWrapperFooter as "choice-wrapper-footer",
	choiceWrapperFooter,
	choiceButton as "choice-button",
	choiceButton,
	choiceButtonImg as "choice-button-img",
	choiceButtonImg
};

export default {
	choices,
	"choice-wrapper": choiceWrapper,
	choiceWrapper,
	"choice-wrapper-body": choiceWrapperBody,
	choiceWrapperBody,
	"choice-wrapper-footer": choiceWrapperFooter,
	choiceWrapperFooter,
	"choice-button": choiceButton,
	choiceButton,
	"choice-button-img": choiceButtonImg,
	choiceButtonImg
};
