/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const select: string;
const selectOpened: string;

export {
	select,
	selectOpened as "select-opened",
	selectOpened
};

export default {
	select,
	"select-opened": selectOpened,
	selectOpened
};
