/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const inputField: string;
const error: string;

export {
	inputField as "input-field",
	inputField,
	error
};

export default {
	"input-field": inputField,
	inputField,
	error
};
