/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const sceneEditor: string;

export {
	sceneEditor as "scene-editor",
	sceneEditor
};

export default {
	"scene-editor": sceneEditor,
	sceneEditor
};
