/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const textareaField: string;
const error: string;
const inputField: string;

export {
	textareaField as "textarea-field",
	textareaField,
	error,
	inputField as "input-field",
	inputField
};

export default {
	"textarea-field": textareaField,
	textareaField,
	error,
	"input-field": inputField,
	inputField
};
