/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const choiceViewer: string;
const choiceTitle: string;
const choiceDescription: string;
const choiceDestination: string;

export {
	choiceViewer as "choice-viewer",
	choiceViewer,
	choiceTitle as "choice-title",
	choiceTitle,
	choiceDescription as "choice-description",
	choiceDescription,
	choiceDestination as "choice-destination",
	choiceDestination
};

export default {
	"choice-viewer": choiceViewer,
	choiceViewer,
	"choice-title": choiceTitle,
	choiceTitle,
	"choice-description": choiceDescription,
	choiceDescription,
	"choice-destination": choiceDestination,
	choiceDestination
};
