/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const diagram: string;
const scene: string;

export {
	diagram,
	scene
};

export default {
	diagram,
	scene
};
