/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const formGroupColumn: string;
const formGroupRow: string;

export {
	formGroupColumn as "form-group-column",
	formGroupColumn,
	formGroupRow as "form-group-row",
	formGroupRow
};

export default {
	"form-group-column": formGroupColumn,
	formGroupColumn,
	"form-group-row": formGroupRow,
	formGroupRow
};
